<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C8IENHF" failures="1" tests="4" name="Test" time="71.716" errors="0" timestamp="2022-08-22T11:17:45 IST">
  <testcase classname="tests.VerificationTest" name="verification" time="0.273"/>
  <testcase classname="tests.SignInTest" name="clickOnSignIn" time="2.204"/>
  <testcase classname="tests.SignInTest" name="clickOnSignIn" time="1.851">
    <failure type="java.lang.AssertionError" message="expected [Failure] but found [Successfull]">
      <![CDATA[java.lang.AssertionError: expected [Failure] but found [Successfull]
at tests.SignInTest.clickOnSignIn(SignInTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- clickOnSignIn -->
  <testcase classname="tests.ClickOnCollectionLick" name="ClickOnCollectionLickTest" time="6.469"/>
</testsuite> <!-- Test -->
